package com.example.Kakeibo.domain.transaction;

public enum Category {
    // 支出
    FOOD, DAILY, TRANSPORT, ENTERTAINMENT, MEDICAL, UTILITIES, RENT,
    COMMUNICATION, INSURANCE, GIFT, MOTHERS_DAY, FATHERS_DAY, OTHER_EXPENSE,
    // 収入
    SALARY, BONUS, SIDE_INCOME, OTHER_INCOME
}
