CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    password      VARCHAR(255) NOT NULL,
    display_name  VARCHAR(50)  NOT NULL,
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users(id),
    name            VARCHAR(50) NOT NULL,
    initial_balance BIGINT      NOT NULL,
    archived        BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS transactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT          NOT NULL REFERENCES users(id),
    account_id BIGINT          NOT NULL REFERENCES accounts(id),
    date       DATE            NOT NULL,
    amount     BIGINT          NOT NULL,
    category   VARCHAR(255)    NOT NULL,
    type       VARCHAR(255)    NOT NULL,
    memo       VARCHAR(100),
    CONSTRAINT transactions_amount_check
        CHECK (amount >= 1),
    CONSTRAINT transactions_category_check
        CHECK (category IN (
            'FOOD', 'DAILY', 'TRANSPORT', 'ENTERTAINMENT', 'MEDICAL',
            'UTILITIES', 'RENT', 'COMMUNICATION', 'INSURANCE',
            'GIFT', 'MOTHERS_DAY', 'FATHERS_DAY', 'OTHER_EXPENSE',
            'SALARY', 'BONUS', 'SIDE_INCOME', 'OTHER_INCOME'
        )),
    CONSTRAINT transactions_type_check
        CHECK (type IN ('INCOME', 'EXPENSE'))
);
