CREATE TABLE IF NOT EXISTS expense_groups (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100) NOT NULL,
    invite_code        VARCHAR(8)   NOT NULL,
    created_by_user_id BIGINT       NOT NULL REFERENCES users(id),
    created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT expense_groups_invite_code_unique UNIQUE (invite_code)
);

CREATE TABLE IF NOT EXISTS group_members (
    group_id  BIGINT    NOT NULL REFERENCES expense_groups(id) ON DELETE CASCADE,
    user_id   BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (group_id, user_id)
);

CREATE TABLE IF NOT EXISTS split_transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id         BIGINT       NOT NULL REFERENCES expense_groups(id),
    total_amount     BIGINT       NOT NULL,
    paid_by_user_id  BIGINT       NOT NULL REFERENCES users(id),
    memo             VARCHAR(200),
    split_date       DATE         NOT NULL,
    created_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT split_transactions_amount_check CHECK (total_amount >= 1)
);

CREATE TABLE IF NOT EXISTS split_shares (
    id                   BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    split_transaction_id BIGINT         NOT NULL REFERENCES split_transactions(id) ON DELETE CASCADE,
    user_id              BIGINT         NOT NULL REFERENCES users(id),
    share_ratio          NUMERIC(5,2)   NOT NULL,
    share_amount         BIGINT         NOT NULL,
    is_settled           BOOLEAN        NOT NULL DEFAULT FALSE,
    settled_at           TIMESTAMP,
    CONSTRAINT split_shares_amount_check CHECK (share_amount >= 1)
);

CREATE TABLE IF NOT EXISTS transfers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id  BIGINT       NOT NULL REFERENCES users(id),
    to_user_id    BIGINT       NOT NULL REFERENCES users(id),
    amount        BIGINT       NOT NULL,
    memo          VARCHAR(200),
    transfer_date DATE         NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    is_settled    BOOLEAN      NOT NULL DEFAULT FALSE,
    settled_at    TIMESTAMP,
    CONSTRAINT transfers_amount_check CHECK (amount >= 1)
);
